




















































































































































































































































































































































































Epoch 1 at 2024-04-24 03:11:40, loss: 0.0169: 100%|██████████| 906/906 [13:26<00:00,  1.12it/s]
Traceback (most recent call last):
  File "/Users/myk/PyPjcts/MedSAM_lite-0424/train_mps-2.py", line 536, in <module>
    main()
  File "/Users/myk/PyPjcts/MedSAM_lite-0424/train_mps-2.py", line 414, in main
    "best_loss": best_loss,
UnboundLocalError: local variable 'best_loss' referenced before assignment